# Generated by Django 6.0 on 2026-01-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('roll_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('class_name', models.IntegerField()),
                ('section', models.CharField(max_length=20)),
                ('dateofbirth', models.CharField(max_length=40)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
