# Generated by Django 6.0 on 2026-01-07 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('roll_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('class_name', models.IntegerField()),
                ('section', models.IntegerField()),
                ('dateofbirth', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Student_problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_title', models.CharField(max_length=200)),
                ('problem', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student_details')),
            ],
        ),
    ]
