# Generated by Django 6.0 on 2026-01-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='section',
            field=models.CharField(max_length=20),
        ),
    ]
