# Generated by Django 6.0 on 2026-01-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_details_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='phone_no',
            field=models.CharField(max_length=30),
        ),
    ]
