# Generated by Django 6.0 on 2026-01-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_student_details_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('dateofbirth', models.CharField(max_length=30)),
            ],
        ),
    ]
